version: '3.8'

services:
  suricata:
    image: docker.io/jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/signatures.rules:/etc/suricata/rules/suratures.rules
      - ./logs/suricata:/var/log/suricata
    command: ["-c", "/etc/suricata/suricata.yaml", "-s", "/etc/suricata/rules/signatures.rules", "-i", "eth0"]
    restart: unless-stopped

  ml-service:
    build: ./ml-service
    container_name: ml-processor
    network_mode: host
    depends_on:
      - suricata
    volumes:
      - ./logs/suricata:/app/logs
      - ./models:/app/models
    restart: unless-stopped

networks:
  monitor-net:
    driver: bridge