FROM python:3.10-slim

WORKDIR /app

# Install curl for debugging
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy both files
COPY batch_processor.py /app/batch_processor.py
COPY actions.py /app/actions.py

CMD ["python", "/app/batch_processor.py"]